language: python
sudo: false
python:
  - 3.5
  - 3.6
  - pypy3
install:
  - pip install -U pip six setuptools codecov
  - pip install -Ur requirements.txt
  - pip install -Ur requirements-dev.txt
script: make coverage
after_success:
  - codecov