version: '2'
services:
  web:
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./src:/opt/py-aquaponic/
    working_dir: /opt/py-aquaponic/
    environment:
      - "DEBUG=${DEBUG}"
      - "SSL=${SSL}"
      - "DATABASE_URL=postgres://postgres:postgres@sql_db/postgres"
      - "REDIS_URL=redis://redis"
      - "DJANGO_SETTINGS_MODULE=core.settings"
    command: ["daphne","core.asgi:channel_layer","--port", "${PORT}","--bind","0.0.0.0","-v2"]
  worker:
    build: .
    volumes:
      - ./src:/opt/py-aquaponic/
    working_dir: /opt/py-aquaponic/
    environment:
      - "DEBUG=${DEBUG}"
      - "DATABASE_URL=postgres://postgres:postgres@sql_db/postgres"
      - "REDIS_URL=redis://redis"
      - "DJANGO_SETTINGS_MODULE=core.settings"
    command: ["/usr/local/bin/pypy3","manage.py","runworker","-v2","--thread","${THREADS}"]
  redis:
    image: "redis:alpine"
  sql_db:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres