# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 14:12
from __future__ import unicode_literals

import core.utils.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actuator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('endpoint', models.CharField(blank=True, default=uuid.uuid4, max_length=255, unique=True)),
                ('strategy', models.CharField(choices=[('iot.actuators.parport.DataPin', 'Parallel Port Pin')], max_length=255)),
                ('strategy_options', jsonfield.fields.JSONField(default={}, null=True)),
            ],
            options={
                'verbose_name': 'Actuator',
            },
        ),
        migrations.CreateModel(
            name='ActuatorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', core.utils.models.DecimalField()),
                ('actuator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='iot.Actuator')),
            ],
        ),
        migrations.CreateModel(
            name='ConversionFormula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.TextField()),
            ],
            options={
                'verbose_name': 'Conversion Formula',
            },
        ),
        migrations.CreateModel(
            name='Magnitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Magnitude',
            },
        ),
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=8, verbose_name='Symbol')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('magnitude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures_units', to='iot.Magnitude')),
            ],
            options={
                'verbose_name': 'Measure Unit',
            },
        ),
        migrations.CreateModel(
            name='PID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('target', core.utils.models.DecimalField()),
                ('kp', core.utils.models.DecimalField()),
                ('ki', core.utils.models.DecimalField()),
                ('kd', core.utils.models.DecimalField()),
            ],
            options={
                'verbose_name': 'PID',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', core.utils.models.DecimalField(verbose_name='Latitude')),
                ('longitude', core.utils.models.DecimalField(verbose_name='Longitude')),
                ('altitude', core.utils.models.DecimalField(verbose_name='Altitude')),
            ],
            options={
                'verbose_name': 'Position',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('endpoint', models.CharField(blank=True, default=uuid.uuid4, max_length=255, unique=True)),
                ('is_virtual', models.BooleanField(default=False, verbose_name='It is a virtual sensor')),
                ('magnitude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='iot.Magnitude')),
                ('measure_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='iot.MeasureUnit')),
                ('position', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='iot.Position')),
            ],
            options={
                'verbose_name': 'Sensor',
            },
            bases=(core.utils.models.ValidateOnSaveMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', core.utils.models.DecimalField()),
                ('raw', jsonfield.fields.JSONField(blank=True, null=True)),
                ('measure_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='iot.MeasureUnit')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='iot.Position')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='iot.Sensor')),
            ],
            options={
                'verbose_name': 'Sensor Data',
                'ordering': ['-time'],
            },
            bases=(core.utils.models.ValidateOnSaveMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SensorFusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(max_length=255, verbose_name='Fusion strategy')),
                ('strategy_options', jsonfield.fields.JSONField(default={})),
                ('inputs', models.ManyToManyField(related_name='consumers', to='iot.Sensor')),
                ('output', models.OneToOneField(help_text='Output virtual sensor', on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='iot.Sensor', verbose_name='Output sensor')),
            ],
            options={
                'verbose_name': 'Sensor Fusion',
            },
        ),
        migrations.AddField(
            model_name='pid',
            name='input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pid_controllers', to='iot.Sensor'),
        ),
        migrations.AddField(
            model_name='pid',
            name='output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pid_controllers', to='iot.Actuator'),
        ),
        migrations.AddField(
            model_name='conversionformula',
            name='from_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_formulas', to='iot.MeasureUnit'),
        ),
        migrations.AddField(
            model_name='conversionformula',
            name='to_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_formulas', to='iot.MeasureUnit'),
        ),
        migrations.AddField(
            model_name='actuatordata',
            name='measure_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iot.MeasureUnit'),
        ),
        migrations.AddField(
            model_name='actuatordata',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iot.Position'),
        ),
        migrations.AddField(
            model_name='actuator',
            name='magnitude',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.Magnitude'),
        ),
        migrations.AddField(
            model_name='actuator',
            name='measure_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iot.MeasureUnit'),
        ),
        migrations.AddField(
            model_name='actuator',
            name='position',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actuator', to='iot.Position'),
        ),
    ]
