# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionFormula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.TextField()),
            ],
            options={
                'verbose_name': 'Conversion Formula',
            },
        ),
        migrations.CreateModel(
            name='Magnitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Magnitude',
            },
        ),
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=8, verbose_name='Symbol')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('magnitude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures_units', to='iot.Magnitude')),
            ],
            options={
                'verbose_name': 'Measure Unit',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('altitude', models.FloatField(verbose_name='Altitude')),
            ],
            options={
                'verbose_name': 'Position',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('magnitude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='iot.Magnitude')),
                ('position', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='iot.Position')),
            ],
            options={
                'verbose_name': 'Sensor',
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', jsonfield.fields.JSONField()),
                ('raw', jsonfield.fields.JSONField(null=True)),
                ('measure_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='iot.MeasureUnit')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='iot.Position')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='iot.Sensor')),
            ],
            options={
                'verbose_name': 'Sensor Data',
            },
        ),
        migrations.AddField(
            model_name='conversionformula',
            name='from_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_formulas', to='iot.MeasureUnit'),
        ),
        migrations.AddField(
            model_name='conversionformula',
            name='to_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_formulas', to='iot.MeasureUnit'),
        ),
    ]
